spring.application.name=sport-backend

spring.datasource.url=jdbc:mysql://localhost:3306/vizsgaremek_sport?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Konyvszobor09

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true